package com.mycompany.trevizanespetinhos.telas;

public class MainScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainScreen.class.getName());

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        // Resize do logo
        javax.swing.ImageIcon iconeOriginal = (javax.swing.ImageIcon) Logo.getIcon();
        
        if (iconeOriginal != null) {
            int novaLargura = 120;
            java.awt.Image imagemRedimensionada = iconeOriginal.getImage().getScaledInstance(novaLargura, -1, java.awt.Image.SCALE_SMOOTH);
            Logo.setIcon(new javax.swing.ImageIcon(imagemRedimensionada));
        }
        
        
        btnMesas.putClientProperty("JButton.buttonType", "roundRect");
        btnHistorico.putClientProperty("JButton.buttonType", "roundRect");
        btnCaixa.putClientProperty("JButton.buttonType", "roundRect");
        btnProdutos.putClientProperty("JButton.buttonType", "roundRect");
        btnRelatorios.putClientProperty("JButton.buttonType", "roundRect");
        ativarBotao(btnMesas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelMargem = new javax.swing.JPanel();
        LateralPanel = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(getBackground());
                // Desenha o arredondamento empurrando a parte direita 30 pixels para fora (reta)
                g2.fillRoundRect(0, 0, getWidth() + 30, getHeight(), 30, 30);
                g2.dispose();
            }
        };
        Logo = new javax.swing.JLabel();
        btnMesas = new javax.swing.JButton();
        btnHistorico = new javax.swing.JButton();
        btnCaixa = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        CenterPanel = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(getBackground());
                // Começa a desenhar 30 pixels antes da esquerda (reta) e arredonda a direita
                g2.fillRoundRect(-60, 0, getWidth() + 30, getHeight(), 30, 30);
                g2.dispose();
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelMargem.setBackground(new java.awt.Color(235, 225, 226));
        PainelMargem.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 60, 20, 60));
        PainelMargem.setLayout(new java.awt.BorderLayout());

        LateralPanel.setBackground(new java.awt.Color(255, 255, 255));
        LateralPanel.setOpaque(false);
        LateralPanel.setPreferredSize(new java.awt.Dimension(200, 600));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TrevizanPequeno.png"))); // NOI18N
        Logo.setAlignmentY(0.0F);
        Logo.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));

        btnMesas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMesas.setForeground(new java.awt.Color(25, 100, 25));
        btnMesas.setText("Mesas");
        btnMesas.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnMesas.addActionListener(this::btnMesasActionPerformed);

        btnHistorico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHistorico.setForeground(new java.awt.Color(25, 100, 25));
        btnHistorico.setText("Histórico");
        btnHistorico.setToolTipText("");
        btnHistorico.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnHistorico.addActionListener(this::btnHistoricoActionPerformed);

        btnCaixa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCaixa.setForeground(new java.awt.Color(25, 100, 25));
        btnCaixa.setText("Caixa");
        btnCaixa.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnCaixa.addActionListener(this::btnCaixaActionPerformed);

        btnProdutos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProdutos.setForeground(new java.awt.Color(25, 100, 25));
        btnProdutos.setText("Produtos");
        btnProdutos.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnProdutos.addActionListener(this::btnProdutosActionPerformed);

        btnRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRelatorios.setForeground(new java.awt.Color(25, 100, 25));
        btnRelatorios.setText("Relatórios");
        btnRelatorios.setToolTipText("");
        btnRelatorios.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnRelatorios.addActionListener(this::btnRelatoriosActionPerformed);

        javax.swing.GroupLayout LateralPanelLayout = new javax.swing.GroupLayout(LateralPanel);
        LateralPanel.setLayout(LateralPanelLayout);
        LateralPanelLayout.setHorizontalGroup(
            LateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LateralPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(LateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(Logo)
                        .addComponent(btnMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRelatorios, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProdutos, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCaixa, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistorico, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        LateralPanelLayout.setVerticalGroup(
            LateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LateralPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo)
                .addGap(18, 18, 18)
                .addComponent(btnMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        PainelMargem.add(LateralPanel, java.awt.BorderLayout.WEST);

        CenterPanel.setBackground(new java.awt.Color(245, 242, 238));
        CenterPanel.setOpaque(false);
        CenterPanel.setLayout(new java.awt.CardLayout());
        PainelMargem.add(CenterPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(PainelMargem, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Método para voltar todos os botões ao estado normal (Fundo branco, texto verde)
private void resetarBotoes() {
    java.awt.Color verdeEscuro = new java.awt.Color(25, 100, 25);
    java.awt.Color branco = java.awt.Color.WHITE;
    
    javax.swing.border.Border bordaInativa = new javax.swing.border.LineBorder(verdeEscuro, 1, true);

    javax.swing.JButton[] botoes = {btnMesas, btnHistorico, btnCaixa, btnProdutos, btnRelatorios};
    
    for (javax.swing.JButton b : botoes) {
        b.setBackground(branco);
        b.setForeground(verdeEscuro);
        
        b.putClientProperty("JButton.buttonType", "roundRect");
        b.putClientProperty("JComponent.arc", 999); 
        b.putClientProperty("JButton.borderColor", verdeEscuro); 
    }
}

// Método para destacar o botão clicado (Fundo verde, texto branco)
private void ativarBotao(javax.swing.JButton botaoAtivo) {
    resetarBotoes(); // Primeiro, limpa todos
    
    java.awt.Color verdeEscuro = new java.awt.Color(25, 100, 25);
    
    // O botão ativo fica totalmente verde (fundo e texto branco)
    botaoAtivo.setBackground(verdeEscuro); 
    botaoAtivo.setForeground(java.awt.Color.WHITE);
}
    
    private void btnMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesasActionPerformed
        ativarBotao(btnMesas);
    }//GEN-LAST:event_btnMesasActionPerformed

    private void btnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoActionPerformed
        ativarBotao(btnHistorico);
    }//GEN-LAST:event_btnHistoricoActionPerformed

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        ativarBotao(btnCaixa);
    }//GEN-LAST:event_btnCaixaActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        ativarBotao(btnProdutos);
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        ativarBotao(btnRelatorios);
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        // 1. Ativa o design do FlatLaf
        com.formdev.flatlaf.FlatLightLaf.setup();

        // 2. Cria e exibe a tela
        java.awt.EventQueue.invokeLater(() -> new MainScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JPanel LateralPanel;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PainelMargem;
    private javax.swing.JButton btnCaixa;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton btnMesas;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnRelatorios;
    // End of variables declaration//GEN-END:variables
}
